### ISSUE TITLE
Exception: The system cannot find the file specified.

### ISSUE THREAD

**Issue by KevinZonda** [imgk/shadow-windows#1]
Same as image:

![image](https://user-images.githubusercontent.com/33132228/114934574-f40cd580-9e31-11eb-8ea5-951d4758794a.png)

**Comment by imgk** [comment]
You should put config.json in the same directory of shadow-windows.exe.

**Comment by KevinZonda** [comment]
> You should put config.json in the same directory of shadow-windows.exe.

Thanks for replying. I added, and it said:

![image](https://user-images.githubusercontent.com/33132228/114935916-a98c5880-9e33-11eb-88fe-bcdb253c72e2.png)

I got this from <https://github.com/imgk/shadow/blob/main/doc/configuration.md>

Config:

![image](https://user-images.githubusercontent.com/33132228/114936033-d17bbc00-9e33-11eb-9028-3479c162854a.png)

**Comment by imgk** [comment]
You should add build tags for shadow-windows as shadow to select supported protocols. And divert is not the default option. You should add build tags to use divert as shadow too.

And you should remember that if your real proxy server is a domain, this config will not work. The domain will be assigned a fake ip. You should read more about the configuration file. You need to add 198.18.0.0/16 to ip_cidr_rules.proxy.

**Comment by KevinZonda** [comment]
> You should add build tags for shadow-windows as shadow to select supported protocols. And divert is not the default option. You should add build tags to use divert as shadow too.
> 
> And you should remember that if your real proxy server is a domain, this config will not work. The domain will be assigned a fake ip. You should read more about the configuration file. You need to add 198.18.0.0/16 to ip_cidr_rules.proxy.

Umm, I tried, but it crashed. I also tried to run shadow directly, it shows:

![image](https://user-images.githubusercontent.com/33132228/114948681-69cf6c00-9e47-11eb-8ffd-fb12f2a5a3b2.png)

I compiled shadow as

```cmd
go build -ldflags="-s -w" -trimpath -tags="divert socks" .\
```
is this correct?

And my proxy server is not a domain, is a IP, and here is my new config:

![image](https://user-images.githubusercontent.com/33132228/114948769-9be0ce00-9e47-11eb-8ed4-0df73b0526c9.png)

Many thanks

**Comment by imgk** [comment]
Can you give more information about your context? If it is a bug, can you open a new issue in shadow’s repository? This error is strange as it shows it is related to golang runtime.

You should replace 127.0.0.1 with your real proxy server as shadow does not capture loopback packets.
