### ISSUE TITLE
shadow 问题

### ISSUE THREAD

**Issue by xiran2018** [imgk/shadow-windows#2]
关于已经关闭的shadow项目，我有一个问题，我在mac本上运行，刚开始的时候，都是正常的，但是过了一会之后，发现一个问题，在程序没有报任何错误的情况下，不能翻墙了，不知道是什么原因（通过观察发现，我在浏览器上输入比如google的网址，发现可能没有收到http的数据包，不知道是不是这个原因，但是为什么收不到这个数据包，我不知道原因），不知道作者有没有遇到这样的情况呢，请指教。

**Comment by imgk** [comment]
本来准备临时关闭项目，现在工作太忙了，你说的问题我也没办法测试，mac上现在也不知道运行情况如何
